### ISSUE TITLE
`dexplode_init` fails if `num_partitions`  is < 2*`num_vcfs`.

### ISSUE THREAD

**Issue by benjeffery** [sgkit-dev/bio2zarr#159] opened 2024-04-30 12:11 UTC
Line 301 in `check_overlap`:
`TypeError '>' not supported between instances of 'NoneType' and 'int'`

**Comment by jeromekelleher** [comment] 2024-04-30 12:55
This is a dupe of #146 I think. There's a workaround queued up in #145

**Comment by jeromekelleher** [comment] 2024-04-30 12:55
I don't see how the number of partitions would induce this though?

**Comment by jeromekelleher** [comment] 2024-05-02 10:12
I'm going to close this as completed in #164, but do reopen if it rears its ugly head again @benjeffery

**Closed by jeromekelleher** 2024-05-02 10:12 UTC
