### ISSUE TITLE
vcf2zarr progress bars aren't updated on Mac

### ISSUE THREAD

**Issue by tomwhite** [sgkit-dev/bio2zarr#201] opened 2024-05-14 10:12 UTC
For example:

```bash
vcf2zarr convert sample.vcf.gz sample.zarr -p 4
    Scan:   0%|                                       | 0.00/1.00 [00:00<?, ?files/s]
 Explode:   0%|                                        | 0.00/9.00 [00:00<?, ?vars/s]
  Encode:   0%|                                            | 0.00/927 [00:00<?, ?B/s]
Finalise: 100%|███████████████████████████████| 21.0/21.0 [00:00<00:00, 1.64karray/s]
```

Running on a bigger VCF is the same: the first three bars are never updated.

This is using Python 3.10 on a Mac M1 (13.5.2) running under Rosetta.

**Comment by jeromekelleher** [comment] 2024-05-14 11:11
Great - this is a dupe of #175 then

**Comment by jeromekelleher** [comment] 2024-05-14 11:14
Seem likely the problem is to do with the shared memory approach taken [here](https://github.com/sgkit-dev/bio2zarr/blob/1ebbfdf8e0f4e93edc26adeb0a27b987bb326609/bio2zarr/core.py#L190). Any insights into what's going on in Mac-land here would be much appreciated!

**Comment by tomwhite** [comment] 2024-05-14 16:15
Mac uses `spawn` by default, while Linux uses `fork` - see https://docs.python.org/3/library/multiprocessing.html#multiprocessing-start-methods.

When I change to use `fork`, it works:

```diff
diff --git a/bio2zarr/core.py b/bio2zarr/core.py
index bd31656..730d85f 100644
--- a/bio2zarr/core.py
+++ b/bio2zarr/core.py
@@ -166,6 +166,7 @@ class ParallelWorkManager(contextlib.AbstractContextManager):
         else:
             self.executor = cf.ProcessPoolExecutor(
                 max_workers=worker_processes,
+                mp_context=multiprocessing.get_context("fork")
             )
         self.futures = []
```

However, it's not clear how safe this is, see https://stackoverflow.com/a/70552892:

>  `fork` __might__ be OK _as long as you don't use threads_

Another suggestion is to use https://docs.python.org/3/library/multiprocessing.html#multiprocessing.Manager.

Finally, in Python 3.14 the default will change away from `fork` for all platforms.

**Comment by tomwhite** [comment] 2024-05-14 16:50
Another way to do this would be to update progress as results are returned from [`results_as_completed`](https://github.com/sgkit-dev/bio2zarr/blob/65ad5cfea782908771891c8c0db93bfdb08207b8/bio2zarr/core.py#L271). This would allow any of the various ways to start a process (`fork`, `spawn` etc).

Would that work?

**Closed** 2024-05-15 08:02 UTC

**Comment by jeromekelleher** [comment] 2024-05-15 08:05
That was super helpful, thanks @tomwhite. I ended up using the shared memory multiprocessing.Value after trying out a lot of different options, and it seemed to the best balance of robustness and responsiveness. I agree the architecture isn't great, coupling over a global variable, but doing progress well is hard.

I switched everything over to "spawn", and got it working again, so should be the same on all platforms now.

**Comment by jeromekelleher** [comment] 2024-05-15 08:57
Would you mind trying out the latest code to see if the progress works OK please @tomwhite?

**Comment by tomwhite** [comment] 2024-05-15 09:40
I just tried it and it works great! Thanks for fixing it @jeromekelleher

BTW I do get a `UserWarning: resource_tracker: There appear to be 3 leaked semaphore objects to clean up at shutdown` but the progress is working now.

**Comment by jeromekelleher** [comment] 2024-05-15 10:12
> BTW I do get a UserWarning: resource_tracker: There appear to be 3 leaked semaphore objects to clean up at shutdown but the progress is working now

Good to know - can you open an issue to track this one please?

**Comment by jeromekelleher** [comment] 2024-05-15 10:12
Any other usability type-things you see on mac would be great to know about btw.
